enum ActionTypes {
  MOVIES_SEARCH_CHANGE = 'app/Movies/MOVIES_SEARCH_CHANGE',
  MOVIES_SORT_CHANGE = 'app/Movies/MOVIES_SORT_CHANGE',
  GET_MOVIES = 'app/Movies/GET_MOVIES',
  GET_MOVIES_SUCCESS = 'app/Movies/GET_MOVIES_SUCCESS',
  GET_MOVIES_FAILURE = 'app/Movies/GET_MOVIES_FAILURE',
  GET_MOVIE_BY_ID = 'app/Movies/GET_MOVIE_BY_ID',
  GET_MOVIE_BY_ID_SUCCESS = 'app/Movies/GET_MOVIE_BY_ID_SUCCESS',
  GET_MOVIE_BY_ID_FAILURE = 'app/Movies/GET_MOVIE_BY_ID_FAILURE',
  DELETE_MOVIE = 'app/Movies/DELETE_MOVIE',
  DELETE_MOVIE_SUCCESS = 'app/Movies/DELETE_MOVIE_SUCCESS',
  DELETE_MOVIE_FAILURE = 'app/Movies/DELETE_MOVIE_FAILURE',
  UPDATE_MOVIE = 'app/Movies/UPDATE_MOVIE',
  UPDATE_MOVIE_SUCCESS = 'app/Movies/UPDATE_MOVIE_SUCCESS',
  UPDATE_MOVIE_FAILURE = 'app/Movies/UPDATE_MOVIE_FAILURE',
  CREATE_MOVIE = 'app/Movies/CREATE_MOVIE',
  CREATE_MOVIE_SUCCESS = 'app/Movies/CREATE_MOVIE_SUCCESS',
  CREATE_MOVIE_FAILURE = 'app/Movies/CREATE_MOVIE_FAILURE',
}

export default ActionTypes;
